inherit_from:
  - http://shopify.github.io/ruby-style-guide/rubocop.yml

AllCops:
  TargetRubyVersion: 2.4.4
  Exclude:
    - 'vendor/bundle/**/*'
Lint/HandleExceptions:
  Exclude:
    - lib/job-iteration.rb
Style/GlobalVars:
  Exclude:
    - lib/job-iteration/integrations/resque.rb
Naming/FileName:
  Exclude:
    - lib/job-iteration.rb
