services:
  - mysql
  - redis-server
language: ruby
rvm:
  - 2.4.5
  - 2.5.3
before_install:
  - gem install bundler
  - mysql -e 'CREATE DATABASE job_iteration_test;'
script:
  - bundle exec rake test
  - bundle exec rubocop
  - bundle exec yardoc --no-output --no-save --no-stats --fail-on-warning

gemfile:
  - 'gemfiles/activejob_5_2.gemfile'
  - 'gemfiles/activejob_edge.gemfile'
