services:
  - mysql
  - redis-server
language: ruby
rvm:
  - 2.4.4
  - 2.5.1
before_install:
  - gem install bundler -v 1.16.0
  - mysql -e 'CREATE DATABASE job_iteration_test;'
script:
  - bundle exec rake test
  - bundle exec rubocop
  - bundle exec yardoc --no-output --no-save --no-stats --fail-on-warning

