services:
  - mysql
  - redis-server
language: ruby
rvm:
  - 2.5
  - 2.6
  - 2.7
before_install:
  - mysql -e 'CREATE DATABASE job_iteration_test;'
script:
  - bundle exec rake test
  - bundle exec rubocop
  - bundle exec yardoc --no-output --no-save --no-stats --fail-on-warning

gemfile:
  - 'gemfiles/rails_5_2.gemfile'
  - 'gemfiles/rails_6_0.gemfile'
  - 'gemfiles/rails_edge.gemfile'
